#!/bin/sh
# Author: Rafael Cavalcanti - rafaelc.org

file="$HOME/Downloads/st_$(date +'%Y-%m-%d_%H%M%S').txt"

if [ -e "$file" ]; then
  notify-send --urgency=critical "Destination already exists."
  exit 1
fi

if cat > "$file"; then
  notify-send st "Saved."
  exit 0
else
  notify-send --urgency=critical "Error saving."
  exit 1
fi

